import { createWriteStream, writeFileSync } from "node:fs";
import {
  AlignmentType,
  BorderStyle,
  Document,
  HeadingLevel,
  Packer,
  PageOrientation,
  Paragraph,
  ShadingType,
  Table,
  TableCell,
  TableRow,
  TextRun,
  VerticalAlign,
  WidthType
} from "docx";
import ExcelJS from "exceljs";
import PDFDocument from "pdfkit";
import { DAYS, PERIODS } from "../domain/constants";
import type { Day, FitnessReport, Period, UniversityData } from "../domain/types";
import type { ScheduleEntry } from "./scheduleFormatter";

const COLORS = {
  navy: "1F4E78",
  blue: "D9EAF7",
  green: "E2F0D9",
  yellow: "FFF2CC",
  gray: "E7E6E6",
  white: "FFFFFF",
  border: "B7B7B7"
};

export async function writeExcelTimetable(
  data: UniversityData,
  entries: ScheduleEntry[],
  report: FitnessReport,
  filePath: string
): Promise<void> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "OptiSchedule";
  workbook.created = new Date();

  addSummaryWorksheet(workbook, data, report);
  addAllSessionsWorksheet(workbook, entries);

  for (const section of data.sections) {
    addSectionWorksheet(workbook, data, section.label, entries);
  }

  await workbook.xlsx.writeFile(filePath);
}

export async function writePdfTimetable(
  data: UniversityData,
  entries: ScheduleEntry[],
  report: FitnessReport,
  filePath: string
): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      layout: "landscape",
      margin: 24,
      bufferPages: true
    });
    const stream = createWriteStream(filePath);

    stream.on("finish", resolve);
    stream.on("error", reject);
    doc.pipe(stream);

    drawPdfCover(doc, data, report);

    for (const section of data.sections) {
      doc.addPage();
      drawPdfSectionTimetable(doc, data, section.label, entries);
    }

    const pages = doc.bufferedPageRange();
    for (let index = pages.start; index < pages.start + pages.count; index += 1) {
      doc.switchToPage(index);
      doc
        .fontSize(7)
        .fillColor("#666666")
        .text(`OptiSchedule | Page ${index + 1} of ${pages.count}`, 24, doc.page.height - 20, {
          align: "right"
        });
    }

    doc.end();
  });
}

export async function writeWordTimetable(
  data: UniversityData,
  entries: ScheduleEntry[],
  report: FitnessReport,
  filePath: string
): Promise<void> {
  const children: Array<Paragraph | Table> = [
    new Paragraph({
      text: "OptiSchedule Timetable Report",
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER
    }),
    paragraph(`Degree: ${data.academic.degreeName}`),
    paragraph(`Current academic year: ${data.academic.currentYear}`),
    paragraph(`Active batches: ${data.academic.activeBatchCodes.join(", ")}`),
    paragraph(`Departments: ${data.departments.map((department) => department.code).join(", ")}`),
    paragraph(`Total rooms: ${data.rooms.length}`),
    paragraph(`Available lab rooms: ${data.rooms.filter((room) => room.isLab).length}`),
    paragraph(`Total teachers: ${data.teachers.length}`),
    paragraph(`Session requirements: ${data.requirements.length}`),
    paragraph(`Fitness score: ${report.score}`),
    paragraph(`Hard constraint violations: ${report.hardViolations}`),
    paragraph("Generated by the Genetic Algorithm backend."),
    spacer()
  ];

  for (const section of data.sections) {
    children.push(
      new Paragraph({
        text: section.label,
        heading: HeadingLevel.HEADING_1
      }),
      buildWordTable(data, section.label, entries),
      spacer()
    );
  }

  const document = new Document({
    sections: [
      {
        properties: {
          page: {
            size: {
              orientation: PageOrientation.LANDSCAPE
            },
            margin: {
              top: 720,
              right: 360,
              bottom: 720,
              left: 360
            }
          }
        },
        children
      }
    ]
  });

  const buffer = await Packer.toBuffer(document);
  writeFileSync(filePath, buffer);
}

function addSummaryWorksheet(
  workbook: ExcelJS.Workbook,
  data: UniversityData,
  report: FitnessReport
): void {
  const worksheet = workbook.addWorksheet("Summary");
  worksheet.columns = [
    { width: 32 },
    { width: 24 }
  ];

  const rows: Array<[string, string | number]> = [
    ["Project", "OptiSchedule"],
    ["Degree", data.academic.degreeName],
    ["Current academic year", data.academic.currentYear],
    ["Degree duration", `${data.academic.degreeYears} years / ${data.academic.totalSemesters} semesters`],
    ["Active batches", data.academic.activeBatchCodes.join(", ")],
    ["Departments", data.departments.map((department) => department.code).join(", ")],
    ["Lecture rooms", data.rooms.filter((room) => !room.isLab).length],
    ["Available lab rooms", data.rooms.filter((room) => room.isLab).length],
    ["Total rooms", data.rooms.length],
    ["Total teachers", data.teachers.length],
    ["Sections", data.sections.length],
    ["Session requirements", data.requirements.length],
    ["Fitness score", report.score],
    ["Hard constraint violations", report.hardViolations],
    ["Soft penalty", report.softPenalty],
    ["Room clashes", report.hardBreakdown.roomClashes],
    ["Teacher clashes", report.hardBreakdown.teacherClashes],
    ["Student clashes", report.hardBreakdown.studentClashes],
    ["Room type mismatches", report.hardBreakdown.roomTypeMismatches],
    ["Capacity violations", report.hardBreakdown.capacityViolations],
    ["Break violations", report.hardBreakdown.breakViolations],
    ["Duration violations", report.hardBreakdown.durationViolations],
    ["Student gap penalty", report.softBreakdown.studentGaps],
    ["Early finish penalty", report.softBreakdown.earlyFinish],
    ["Active campus days penalty", report.softBreakdown.studentActiveDays],
    ["Campus span penalty", report.softBreakdown.campusSpan]
  ];

  worksheet.addRow(["Metric", "Value"]);
  worksheet.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } };
  worksheet.getRow(1).fill = solidFill(COLORS.navy);

  for (const row of rows) {
    worksheet.addRow(row);
  }

  styleWorksheetBorders(worksheet);
}

function addAllSessionsWorksheet(workbook: ExcelJS.Workbook, entries: ScheduleEntry[]): void {
  const worksheet = workbook.addWorksheet("All Sessions");
  worksheet.columns = [
    { header: "Department", key: "department", width: 14 },
    { header: "Batch", key: "batch", width: 10 },
    { header: "Semester", key: "semester", width: 10 },
    { header: "Section", key: "section", width: 34 },
    { header: "Course Code", key: "courseCode", width: 14 },
    { header: "Course Name", key: "courseName", width: 34 },
    { header: "Type", key: "sessionType", width: 10 },
    { header: "Teacher", key: "teacher", width: 26 },
    { header: "Room", key: "room", width: 28 },
    { header: "Day", key: "day", width: 14 },
    { header: "Start", key: "start", width: 10 },
    { header: "End", key: "end", width: 10 },
    { header: "Periods", key: "durationPeriods", width: 10 }
  ];

  worksheet.addRows(entries);
  worksheet.views = [{ state: "frozen", ySplit: 1 }];
  worksheet.autoFilter = "A1:M1";
  worksheet.getRow(1).font = { bold: true, color: { argb: "FFFFFFFF" } };
  worksheet.getRow(1).fill = solidFill(COLORS.navy);
  styleWorksheetBorders(worksheet);
}

function addSectionWorksheet(
  workbook: ExcelJS.Workbook,
  data: UniversityData,
  sectionLabel: string,
  entries: ScheduleEntry[]
): void {
  const worksheet = workbook.addWorksheet(toWorksheetName(sectionLabel));
  worksheet.pageSetup = {
    orientation: "landscape",
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 1,
    paperSize: 9
  };
  worksheet.columns = [
    { width: 14 },
    ...PERIODS.map(() => ({ width: 24 }))
  ];

  worksheet.mergeCells(1, 1, 1, PERIODS.length + 1);
  const titleCell = worksheet.getCell(1, 1);
  titleCell.value = sectionLabel;
  titleCell.font = { bold: true, size: 16, color: { argb: "FFFFFFFF" } };
  titleCell.alignment = { horizontal: "center", vertical: "middle" };
  titleCell.fill = solidFill(COLORS.navy);
  worksheet.getRow(1).height = 24;

  const headerRow = worksheet.addRow(["Day", ...PERIODS.map((period) => period.label)]);
  headerRow.font = { bold: true, color: { argb: "FFFFFFFF" } };
  headerRow.height = 22;
  headerRow.eachCell((cell) => {
    cell.fill = solidFill(COLORS.navy);
    cell.alignment = { horizontal: "center", vertical: "middle", wrapText: true };
  });

  for (const day of DAYS) {
    const row = worksheet.addRow([day]);
    const rowNumber = row.number;
    row.height = 88;
    row.getCell(1).font = { bold: true };
    row.getCell(1).fill = solidFill(COLORS.blue);
    row.getCell(1).alignment = { horizontal: "center", vertical: "middle" };

    const consumedPeriodIds = new Set<string>();

    for (const period of PERIODS) {
      const columnNumber = period.index + 2;
      const cell = row.getCell(columnNumber);

      if (consumedPeriodIds.has(period.id)) {
        continue;
      }

      if (period.isBreak) {
        cell.value = "Lunch / Namaz";
        cell.fill = solidFill(COLORS.gray);
        styleExcelCell(cell, true);
        continue;
      }

      const startingEntries = getStartingEntries(entries, sectionLabel, day, period);
      if (startingEntries.length === 0) {
        cell.value = "";
        styleExcelCell(cell, false);
        continue;
      }

      const span = getCellSpan(startingEntries, data.periods, period);
      cell.value = startingEntries.map(formatDetailedCell).join("\n---\n");
      cell.fill = solidFill(startingEntries.some((entry) => entry.sessionType === "LAB") ? COLORS.green : COLORS.yellow);
      styleExcelCell(cell, true);

      if (span > 1) {
        worksheet.mergeCells(rowNumber, columnNumber, rowNumber, columnNumber + span - 1);
        for (let offset = 1; offset < span; offset += 1) {
          const consumedPeriod = data.periods.find(
            (candidate) => candidate.index === period.index + offset
          );
          if (consumedPeriod) {
            consumedPeriodIds.add(consumedPeriod.id);
          }
        }
      }
    }
  }

  styleWorksheetBorders(worksheet);
}

function drawPdfCover(
  doc: PDFKit.PDFDocument,
  data: UniversityData,
  report: FitnessReport
): void {
  doc.rect(0, 0, doc.page.width, 92).fill("#1F4E78");
  doc
    .fillColor("#FFFFFF")
    .fontSize(24)
    .text("OptiSchedule", 36, 30)
    .fontSize(13)
    .text("Generated University Timetable", 36, 60);

  doc.fillColor("#111111").fontSize(12);
  const rows = [
    ["Departments", data.departments.map((department) => department.code).join(", ")],
    ["Degree", data.academic.degreeName],
    ["Current year", String(data.academic.currentYear)],
    ["Active batches", data.academic.activeBatchCodes.join(", ")],
    ["Sections", String(data.sections.length)],
    ["Total rooms", String(data.rooms.length)],
    ["Lecture rooms", String(data.rooms.filter((room) => !room.isLab).length)],
    ["Lab rooms", String(data.rooms.filter((room) => room.isLab).length)],
    ["Teachers", String(data.teachers.length)],
    ["Session requirements", String(data.requirements.length)],
    ["Fitness score", String(report.score)],
    ["Hard constraint violations", String(report.hardViolations)],
    ["Soft penalty", String(report.softPenalty)]
  ];

  let y = 130;
  for (const [label, value] of rows) {
    doc.font("Helvetica-Bold").text(label, 60, y, { width: 180 });
    doc.font("Helvetica").text(value, 250, y, { width: 420 });
    y += 24;
  }
}

function drawPdfSectionTimetable(
  doc: PDFKit.PDFDocument,
  data: UniversityData,
  sectionLabel: string,
  entries: ScheduleEntry[]
): void {
  const margin = 24;
  const titleY = 28;
  const tableTop = 72;
  const dayColumnWidth = 68;
  const periodColumnWidth = (doc.page.width - margin * 2 - dayColumnWidth) / PERIODS.length;
  const headerHeight = 30;
  const rowHeight = 84;

  doc.fillColor("#111111").font("Helvetica-Bold").fontSize(15).text(sectionLabel, margin, titleY);
  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor("#555555")
    .text("Theory sessions use yellow cells. Lab/PR blocks use green cells.", margin, titleY + 22);

  drawPdfCell(doc, "Day", margin, tableTop, dayColumnWidth, headerHeight, "#1F4E78", "#FFFFFF", 8, true);
  PERIODS.forEach((period) => {
    drawPdfCell(
      doc,
      period.label,
      margin + dayColumnWidth + period.index * periodColumnWidth,
      tableTop,
      periodColumnWidth,
      headerHeight,
      "#1F4E78",
      "#FFFFFF",
      7,
      true
    );
  });

  DAYS.forEach((day, dayIndex) => {
    const rowY = tableTop + headerHeight + dayIndex * rowHeight;
    drawPdfCell(doc, day, margin, rowY, dayColumnWidth, rowHeight, "#D9EAF7", "#111111", 8, true);

    const consumedPeriodIds = new Set<string>();

    for (const period of PERIODS) {
      if (consumedPeriodIds.has(period.id)) {
        continue;
      }

      const x = margin + dayColumnWidth + period.index * periodColumnWidth;

      if (period.isBreak) {
        drawPdfCell(
          doc,
          "Lunch\nNamaz",
          x,
          rowY,
          periodColumnWidth,
          rowHeight,
          "#E7E6E6",
          "#111111",
          7,
          true
        );
        continue;
      }

      const startingEntries = getStartingEntries(entries, sectionLabel, day, period);
      if (startingEntries.length === 0) {
        drawPdfCell(doc, "", x, rowY, periodColumnWidth, rowHeight, "#FFFFFF", "#111111", 7, false);
        continue;
      }

      const span = getCellSpan(startingEntries, data.periods, period);
      const width = periodColumnWidth * span;
      drawPdfCell(
        doc,
        startingEntries.map(formatCompactCell).join("\n---\n"),
        x,
        rowY,
        width,
        rowHeight,
        startingEntries.some((entry) => entry.sessionType === "LAB") ? "#E2F0D9" : "#FFF2CC",
        "#111111",
        6.4,
        false
      );

      for (let offset = 1; offset < span; offset += 1) {
        const consumedPeriod = data.periods.find(
          (candidate) => candidate.index === period.index + offset
        );
        if (consumedPeriod) {
          consumedPeriodIds.add(consumedPeriod.id);
        }
      }
    }
  });
}

function buildWordTable(
  data: UniversityData,
  sectionLabel: string,
  entries: ScheduleEntry[]
): Table {
  const rows: TableRow[] = [
    new TableRow({
      tableHeader: true,
      children: [
        wordCell("Day", COLORS.navy, true),
        ...PERIODS.map((period) => wordCell(period.label, COLORS.navy, true))
      ]
    })
  ];

  for (const day of DAYS) {
    const cells: TableCell[] = [wordCell(day, COLORS.blue, true)];
    const consumedPeriodIds = new Set<string>();

    for (const period of PERIODS) {
      if (consumedPeriodIds.has(period.id)) {
        continue;
      }

      if (period.isBreak) {
        cells.push(wordCell("Lunch / Namaz", COLORS.gray, true));
        continue;
      }

      const startingEntries = getStartingEntries(entries, sectionLabel, day, period);
      if (startingEntries.length === 0) {
        cells.push(wordCell("", COLORS.white, false));
        continue;
      }

      const span = getCellSpan(startingEntries, data.periods, period);
      cells.push(
        wordCell(
          startingEntries.map(formatCompactCell).join("\n---\n"),
          startingEntries.some((entry) => entry.sessionType === "LAB") ? COLORS.green : COLORS.yellow,
          false,
          span
        )
      );

      for (let offset = 1; offset < span; offset += 1) {
        const consumedPeriod = data.periods.find(
          (candidate) => candidate.index === period.index + offset
        );
        if (consumedPeriod) {
          consumedPeriodIds.add(consumedPeriod.id);
        }
      }
    }

    rows.push(new TableRow({ children: cells }));
  }

  return new Table({
    width: {
      size: 100,
      type: WidthType.PERCENTAGE
    },
    rows
  });
}

function getStartingEntries(
  entries: ScheduleEntry[],
  sectionLabel: string,
  day: Day,
  period: Period
): ScheduleEntry[] {
  return entries.filter(
    (entry) => entry.section === sectionLabel && entry.day === day && entry.start === period.start
  );
}

function getCellSpan(entries: ScheduleEntry[], periods: Period[], startPeriod: Period): number {
  const maxDuration = Math.max(...entries.map((entry) => entry.durationPeriods));
  const block = periods.filter(
    (period) => period.index >= startPeriod.index && period.index < startPeriod.index + maxDuration
  );

  if (block.some((period) => period.isBreak)) {
    return 1;
  }

  return Math.max(1, block.length);
}

function formatDetailedCell(entry: ScheduleEntry): string {
  return [
    `${entry.courseCode} (${entry.sessionType})`,
    entry.courseName,
    entry.teacher,
    entry.room
  ].join("\n");
}

function formatCompactCell(entry: ScheduleEntry): string {
  return [
    `${entry.courseCode} ${entry.sessionType}`,
    entry.courseName,
    entry.teacher,
    entry.room
  ].join("\n");
}

function drawPdfCell(
  doc: PDFKit.PDFDocument,
  text: string,
  x: number,
  y: number,
  width: number,
  height: number,
  fillColor: string,
  textColor: string,
  fontSize: number,
  bold: boolean
): void {
  doc.rect(x, y, width, height).fillAndStroke(fillColor, "#B7B7B7");
  doc
    .fillColor(textColor)
    .font(bold ? "Helvetica-Bold" : "Helvetica")
    .fontSize(fontSize)
    .text(text, x + 3, y + 5, {
      width: width - 6,
      height: height - 8,
      align: "center",
      ellipsis: true
    });
}

function styleExcelCell(cell: ExcelJS.Cell, bold: boolean): void {
  cell.alignment = {
    horizontal: "center",
    vertical: "middle",
    wrapText: true
  };
  cell.font = {
    bold,
    size: 9
  };
}

function styleWorksheetBorders(worksheet: ExcelJS.Worksheet): void {
  worksheet.eachRow((row) => {
    row.eachCell((cell) => {
      cell.border = {
        top: { style: "thin", color: { argb: `FF${COLORS.border}` } },
        left: { style: "thin", color: { argb: `FF${COLORS.border}` } },
        bottom: { style: "thin", color: { argb: `FF${COLORS.border}` } },
        right: { style: "thin", color: { argb: `FF${COLORS.border}` } }
      };
      cell.alignment = {
        vertical: "middle",
        wrapText: true
      };
    });
  });
}

function solidFill(color: string): ExcelJS.Fill {
  return {
    type: "pattern",
    pattern: "solid",
    fgColor: {
      argb: `FF${color}`
    }
  };
}

function wordCell(
  text: string,
  fillColor: string,
  bold: boolean,
  columnSpan = 1
): TableCell {
  return new TableCell({
    columnSpan,
    shading: {
      type: ShadingType.CLEAR,
      color: "auto",
      fill: fillColor
    },
    verticalAlign: VerticalAlign.CENTER,
    borders: {
      top: { style: BorderStyle.SINGLE, size: 1, color: COLORS.border },
      bottom: { style: BorderStyle.SINGLE, size: 1, color: COLORS.border },
      left: { style: BorderStyle.SINGLE, size: 1, color: COLORS.border },
      right: { style: BorderStyle.SINGLE, size: 1, color: COLORS.border }
    },
    children: text.split("\n").map(
      (line) =>
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [
            new TextRun({
              text: line,
              bold,
              size: bold ? 16 : 13
            })
          ]
        })
    )
  });
}

function paragraph(text: string): Paragraph {
  return new Paragraph({
    children: [new TextRun(text)]
  });
}

function spacer(): Paragraph {
  return new Paragraph({
    children: [new TextRun("")]
  });
}

function toWorksheetName(value: string): string {
  return value.replace(/[\\/*[\]:?]/g, " ").slice(0, 31);
}
